### PR TITLE
Udata 1.4 updates

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR:
- upgrade to webpack 4 and latest plugins
- removes the security warning
- upgrade all dependencies
- fix udata 1.4 discussions display
- fix udata 1.4 resources display

screenshot-data xps-2018 07 30-10-54-09

### CODE REVIEW

**Comment by petzlux** [comment]
I have problems getting this PR to work. Cant find the CSS and JS resources 

````
localhost/:69 GET http://localhost:7000/static/common.css?_=1.4.0 404 (NOT FOUND)
localhost/:1842 GET http://localhost:7000/static/common.js?_=1.4.0 404 (NOT FOUND)
localhost/:70 GET http://localhost:7000/static/home.css?_=1.4.0 404 (NOT FOUND)
localhost/:1843 GET http://localhost:7000/static/home.js?_=1.4.0 404 (NOT FOUND)
````

**Review by petzlux — CHANGES_REQUESTED** [review]
Get missing CSS and JS resources errors after rebuilding the docker-compose

**Comment by noirbizarre** [comment]
This is not directly related to this PR: `common.{css,js}` and `home.{css,js}` are related to `udata` only.
There is no change on the docker-compose stack and this might have be broken for a while.
I fixed it in the last commit.

**Comment by noirbizarre** [comment]
PS: if you perform a release after this merge, I advise you to increment the version minor and release a `1.1.0`.
- `bumpr -mdv` to preview
- `bumpr -m --skip-tests` to publish

**Comment by petzlux** [comment]
@noirbizarre Do you see any obstacle to immediately in this PR update to udata 1.5 ?

**Pull request merged**
